/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fileserver_distributed;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.io.*;
import java.text.*;
import java.util.Arrays;


import java.io.File;
import java.net.Socket;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

/**
 *
 * @author mostafa
 */
public class Register extends javax.swing.JFrame {
    private Socket s ;
    private DataInputStream dis;
    private DataOutputStream dos;
    private String srvr_msg ;  
    /**
     * Creates new form Register
     */
    public Register() {
        try{
            s = new Socket("127.0.0.1", 1234);
//            s = new Socket("192.168.43.250", 1234);
           dis = new DataInputStream(s.getInputStream());
           dos = new DataOutputStream(s.getOutputStream());
            System.out.println("client Side");
            System.out.println(dis.readUTF());
            initComponents();
//           users = new ArrayList<user>();
//           populateArrayList();
        }
        catch(IOException ex){
            try{
                JOptionPane.showMessageDialog(null,"some thing happend during connection!");

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "some thing happend in client side!");
            }
          

        }
    }
    
    
//    
//     public void populateArrayList(){
//        try {
////            this.users.addAll(this.dis.readUTF());
//             String lol = this.dis.readUTF();
//            FileInputStream file = new FileInputStream(this.srvr_msg);
//            
//            ObjectInputStream inputFile = new ObjectInputStream(file);
//            boolean endOfFile = false;
//            while (!endOfFile) {                
//                try {
//                    users.add((user)inputFile.readObject());
//                } catch (EOFException e) {
//                    endOfFile = true;
//                }
//                catch (Exception f) {
////                    JOptionPane.showMessageDialog(null, f.getMessage());
//                    JOptionPane.showMessageDialog(null, f.getMessage());
//                }
//            }
//            inputFile.close();
//            
//        } catch (IOException e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//    }
//    
//     
//     
//    public void saveUsersToFile(){
//        try {
//            FileOutputStream file = new FileOutputStream("users.dat");
//            ObjectOutputStream outputFile = new ObjectOutputStream(file);
//            
//            for (int i = 0; i < users.size(); i++) {
//                outputFile.writeObject(users.get(i));
//            }
//            outputFile.close();
//            JOptionPane.showMessageDialog(null, "succefuly Registered!");
//            
//            new Home(Integer.toString(users.size())).setVisible(true);
//            this.dispose();
//            
//        } catch (IOException e) {
////            JOptionPane.showMessageDialog(null, "hello t");
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//         catch (Exception e) {
////            JOptionPane.showMessageDialog(null, "hello t");
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//    }
//    
//    
//    private static void createDirectory(String pathName){
//        File files = new File(pathName);
//        if(!files.exists()){ //if the file folder does not exist
//            if(files.mkdirs()){ //if you want to create sub folder. you can change mkdir to mkdirs
//                System.out.println("Directory Created in"+files.getAbsolutePath());
//            }
//            else{
//                System.out.println("Problem Occured creating directory"); 
//            }
//        }
//        else{
//            System.out.println("Directory "+files.getAbsolutePath()+" already exist !");
//        }
//    }
//    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.pink);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Register");

        jLabel1.setText("Email:");

        jLabel2.setText("Password:");

        jLabel3.setText("Rewrite Password:");

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().isEmpty() || jTextField4.getText().isEmpty() ||
             jTextField3.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "please enter all fields");
        }
        else{
             String email = jTextField1.getText().trim();
            String password = jTextField4.getText().trim();
            String RePassword = jTextField3.getText().trim();
            
            if(!(password.equals(RePassword)) ){
                JOptionPane.showMessageDialog(null, "Two Passwords are not identical!, please try again");
                jTextField4.setText(null);
                    jTextField3.setText(null);
            }
            else{
                try{
                    String AlreadyReg = "false";
//                    System.out.println(dis.readUTF());
//                    System.out.println(dis.readUTF());
//                    if(dis.readUTF().equals("error during fetching users!")){
//                        System.out.println(dis.readUTF());
//                        this.dispose();
//                        new Register().setVisible(true);
//                    }
//                    for (int i = 0; i < users.size(); i++) {
//                        if(email.equals(users.get(i).getEmail())){
//                            JOptionPane.showMessageDialog(null, "you are already registered!");
//                            jTextField4.setText(null);
//                            jTextField3.setText(null);
//                            this.dispose();
//                            AlreadyReg = true;
//                            break;
//                        }
//                    }
//                    AlreadyReg = dis.readUTF();
//                    
//                    if(AlreadyReg.equals("true")){
//                        JOptionPane.showMessageDialog(null, "you are already registered!");
//                        this.dispose();
//                        new login().setVisible(true);
//                    }
                    
//                    else{
                        
//                        try{
                              int []indx = new int [200];
                            Arrays.fill(indx, 0);
                            
                             for (int i = 0; i < email.length(); i++) {
                                if( (Character)email.charAt(i) =='@' && i!=0 && i!=((int)email.length()-2) && i!=((int)email.length()-1 )){
                                   if((Character)email.charAt(i-1)!='.' && (Character)email.charAt(i+1)!='.' 
                                           && (Character)email.charAt(i-1)!='@' && (Character)email.charAt(i+1)!='@'){
                                   indx['@'] ++;
                               }
                             }
                            }

                           if(indx['@'] == 1){
                               System.out.println(dis.readUTF());
                   
                                System.out.println((String)email);
                                dos.writeUTF(email);
                                dos.flush();
                                System.out.println(dis.readUTF());
                                dos.writeUTF(password);
                                dos.flush();
//                                  AlreadyReg = dis.readUTF();
//                                System.out.println("true!");
                            String lol  = dis.readUTF();
                                System.out.println(lol);
                                
                                    if(lol.equals("true")){
                                        JOptionPane.showMessageDialog(null, "you are already registered!");
                                         this.dispose();
                                        new login().setVisible(true);
                                       
                                    }
//                                String stateOfRegister = dis.readUTF();
                                    
                                 else if(lol.equals("succefuly Registered!"))
                                {
                                    
                                   String users_size = dis.readUTF();
//                                    new Home(Integer.toString(users.size())).setVisible(true);
                                    System.out.println("from successfuly registe!"+lol);
//                                    System.out.println("from successfuly registe!"+dis.readUTF());
                                    try{
                                    if(dis!=null)
                                        dis.close();
                                     if(dos!=null)
                                        dos.close();
                                     if(s!=null)
                                        s.close();
                                    }
                                    catch(Exception ex){
                                        JOptionPane.showMessageDialog(null, "refused to close!");
                                    }
                                    this.dispose();
                                    new Home(users_size).setVisible(true);
                                    
                                    
                                    
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "failed to register!");
                                }
//                                user newUser = new user((String)email ,(String) password);
//                                       users.add(newUser);
////                                       new folder(newUser.getId())
//                                       createDirectory("/home/mostafa/NetBeansProjects/fileserver_distributed/"+users.size()+"/home");
//                                       
//                                       saveUsersToFile();   
                           }
                           else{
                                JOptionPane.showMessageDialog(null,"this email is not valid");
           //                        throw new Exception("not valid email");
                                   this.dispose();
                                   new Register().setVisible(true);
                            }
                            
                            
//                           user newUser = new user((String)email ,(String) password);
//                            users.add(newUser);
//                            saveUsersToFile();
//                        }
//                        catch(Exception e){
//                            JOptionPane.showMessageDialog(null, e.getMessage());
//
//                }
                   
//                    }
//                    dis.close();
//                    dos.close();
//                    s.close();
//                    new Home().setVisible(true);
//                    this.dispose();
                }
            
                catch(IOException e){
//                    JOptionPane.showMessageDialog(null, e.getMessage());
                    JOptionPane.showMessageDialog(null, "after try something happen!");

                }
                
            }
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
